### ISSUE TITLE
fotos UI freezes when trying to connect

### ISSUE THREAD

**Issue by gitaaron** [functionland/fotos#205]
It happens when Fotos is trying to upload a photo to the Box and it responds in a way that Fotos is not handling.

If I stop  the Box application then the Fotos UI becomes responsive again.

To help reproduce it maybe you can just add a sleep in Box?

Mahdi mentioned that a background task did not solve the issue meaning it is probably entering an infinite loop and eating up cycles or something.

**Comment by ghorbani-m** [comment]
I did some investigation on how we can run a piece of code that blocks the Js thread on react-native and tried some packages like [react-native-multithreading](https://www.npmjs.com/package/react-native-multithreading) and [react-native-bg-thread](https://www.npmjs.com/package/react-native-bg-thread) but none of them worked

What I understood we need to implement multi-threading on [react-native-fula](https://github.com/functionland/react-native-fula) while streaming the data.

**Comment by farhoud** [comment]
@gitaaron @ghorbani-m 
> What I understood we need to implement multi-threading on [react-native-fula](https://github.com/functionland/react-native-fula) while streaming the data.

Then we have 2 problems. :D

react native design single threaded and go-fula run on main UI thread (not JS thread). so the thing goes south it break the main thread. 
And by reading code of Libp2p dial and connect. [ref](https://github.com/libp2p/go-libp2p/blob/e477efda73b8f746d201c208076d45a6d23f07fb/p2p/host/basic/basic_host.go#L776) you will see that libp2p already is multi thread code. So don't think adding thread fix's anything.
I think the main reason on freezes is current go-fula-0.4.2 has some bug in error handling (the code will panic) that i will fix after.
[ ] - https://github.com/functionland/go-fula/issues/18

**Comment by ghorbani-m** [comment]
@farhoud
I don't think the freeze issue is because of some bugs or error handling on go-fula.
I did some tests and called other blocker codes on Fotos and got the same result as calling go-fula methods.

My solution is to implement _multi-threading_ on `react-native-fula` on the **Java** side while we are bridging the codes.

**Comment by farhoud** [comment]
@ghorbani-m 
The underlining code in go side is multi-threaded and if you still blocked means :
- the react-native does not respect the module threading. 
- I don't think if the threading does not work on go side it would work on JAVA.

**Comment by farhoud** [comment]
I think the new architecture and JSI will solve the problem but they are at there early stage and not ready for production

**Comment by ghorbani-m** [comment]
> @ghorbani-m The underlining code in go side is multi-threaded and if you still blocked means :
> 
> * the react-native does not respect the module threading.
> * I don't think if the threading does not work on go side it would work on JAVA.
> 
> My experience is accept react-native framework limitation. [ref](https://reactnative.dev/docs/native-modules-android#threading)

I added multi-thread feature to the `react-native-fula` `android `module and got a test so it works like what we expected.
@farhoud can you please have a look at [this PR](https://github.com/functionland/react-native-fula/pull/17) and if it is ok then merge it and release a new build?
