### ISSUE TITLE
Storyhighlights time bar issue while moving (forward | backward) between the stories 

### ISSUE THREAD

**Issue by emadbaqeri** [functionland/fotos#278]
The width of the time bar is fixed and not going to start from the base position that it should be while moving to the previous story.

**Comment by ghorbani-m** [comment]
@emadbaqeri Story highlight is changed in the previous refactor, please have a look at that on the develop branch

**Comment by emadbaqeri** [comment]
> @emadbaqeri Story highlight is changed in the previous refactor, please have a look at that on the develop branch

There is another issue with that which Ehsan mentioned yesterday. I have opened a new issue about #279.
