### ISSUE TITLE
Redesign the time-bar component

### ISSUE THREAD

**Issue by ghorbani-m** [functionland/fotos#299]
In the [current component](https://github.com/functionland/fotos/tree/develop/app/components/timer-progress), there is just one line-timer animation. we need to change it so that like the below screenshot.

![image](https://user-images.githubusercontent.com/16715868/191804699-b0639a09-8437-47be-86bd-35c784a339c6.png)

**Solution prorierties:**

1. Using SVG animation, FYI, clipPath has[ an animation issue](https://github.com/react-native-svg/react-native-svg/issues/1719) on Android, but works on IOS,
2. Using Flatlist

**Comment by abdymm** [comment]
hi @ghorbani-m did you resolve this by downgrading the lib?

**Comment by ghorbani-m** [comment]
Hi @abdymm ,
No, downgrading did not work for me, I tested all solutions and nothing worked at least for me!
Finally, I implemented my component by react-native-reanimated
