### ISSUE TITLE
Dark Mode!

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [functionland/fotos#33]
Would be cool to have Dark Mode integrated earlier, saves us time if we implement it incrementally.

**Comment by emadbaqeri** [comment]
Hey there, is there anyone working on this? I think I can do this. Can you please assign this to me?

**Comment by emadbaqeri** [comment]
@ehsan6sha @keyvan-m-sadeghi I think this is going to be done with ThemeProvider wrapper module around the whole App module, yes? or maybe I'm going to utilize the react-native-paper ThemeProvider or DarkTheme provider. If I'm not right please correct me.

**Comment by ehsan6sha** [comment]
> @ehsan6sha @keyvan-m-sadeghi I think this is going to be done with ThemeProvider wrapper module around the whole App module, yes? or maybe I'm going to utilize the react-native-paper ThemeProvider or DarkTheme provider. If I'm not right please correct me.

I trust you :D  I say anything that is open source and has a good community and requires adding less complications works

**Comment by emadbaqeri** [comment]
> > @ehsan6sha @keyvan-m-sadeghi I think this is going to be done with ThemeProvider wrapper module around the whole App module, yes? or maybe I'm going to utilize the react-native-paper ThemeProvider or DarkTheme provider. If I'm not right please correct me.
> 
> I trust you :D I say anything that is open source and has a good community and requires adding less complications works. I suggest something that is of material design type so that we can leverage in all themings

Thank you really much, glad to hear. So I think we should go up with the themeprovider of the react navigation it self for having more consistant user interface and less complication.

**Comment by emadbaqeri** [comment]
@ehsan6sha Hey, today I started to implement the dark mode for the app. Are we going to have a settings in our app for controlling the dark mode of the app on it's inside implementation or we are just going to obbey from the device settings and device theme. I think we can have this item in settings menu and a global context for storing this as state on it, if the device theme mode was dark we can detect it at the first time we are running the app and decided what to do with the global theme of the app.

**Comment by ehsan6sha** [comment]
> @ehsan6sha Hey, today I started to implement the dark mode for the app. Are we going to have a settings in our app for controlling the dark mode of the app on it's inside implementation or we are just going to obbey from the device settings and device theme. I think we can have this item in settings menu and a global context for storing this as state on it, if the device theme mode was dark we can detect it at the first time we are running the app and decided what to do with the global theme of the app.

Since we need a settings page regardless of theme, I believe the best is to have the control option in settings to give the user full control

**Comment by emadbaqeri** [comment]
> > @ehsan6sha Hey, today I started to implement the dark mode for the app. Are we going to have a settings in our app for controlling the dark mode of the app on it's inside implementation or we are just going to obbey from the device settings and device theme. I think we can have this item in settings menu and a global context for storing this as state on it, if the device theme mode was dark we can detect it at the first time we are running the app and decided what to do with the global theme of the app.
> 
> Since we need a settings page regardless of theme, I believe the best is to have the control option in settings to give the user full control

So then I'm going to implement that with redux like library, these days I'm just somehow living in the office and working really on my companies projects maybe it may take a bit for fixing this issue. Is that going to be a problem?

**Comment by ehsan6sha** [comment]
> > > @ehsan6sha Hey, today I started to implement the dark mode for the app. Are we going to have a settings in our app for controlling the dark mode of the app on it's inside implementation or we are just going to obbey from the device settings and device theme. I think we can have this item in settings menu and a global context for storing this as state on it, if the device theme mode was dark we can detect it at the first time we are running the app and decided what to do with the global theme of the app.
> > 
> > 
> > Since we need a settings page regardless of theme, I believe the best is to have the control option in settings to give the user full control
> 
> So then I'm going to implement that with redux like library for giving user full controll on the theme state, these days I'm just somehow living in the office and working really on my companies projects maybe it may take a bit for fixing this issue. Is that going to be a problem?

Thank you Emad. No problem at all and it's very much appreciated. Just two notes from my experience which we can discuss if you think otherwise:

1- please use recoil (it's already in library list and we used recoil to manage states and not redux)

2- please try to keep state changes to minimum and per your experience use animated or reanimated (for example for hiding and showing elements I used opacity and reanimated instead of a boolean state change to minimize re-renders).

**Comment by emadbaqeri** [comment]
> > > > @ehsan6sha Hey, today I started to implement the dark mode for the app. Are we going to have a settings in our app for controlling the dark mode of the app on it's inside implementation or we are just going to obbey from the device settings and device theme. I think we can have this item in settings menu and a global context for storing this as state on it, if the device theme mode was dark we can detect it at the first time we are running the app and decided what to do with the global theme of the app.
> > > 
> > > 
> > > Since we need a settings page regardless of theme, I believe the best is to have the control option in settings to give the user full control
> > 
> > So then I'm going to implement that with redux like library for giving user full controll on the theme state, these days I'm just somehow living in the office and working really on my companies projects maybe it may take a bit for fixing this issue. Is that going to be a problem?
> 
> Thank you Emad. No problem at all and it's very much appreciated. Just two notes from my experience which we can discuss if you think otherwise:
> 
> 1- please use recoil (it's already in library list and we used recoil to manage states and not redux)
> 
> 2- please try to keep state changes to minimum and per your experience use animated or reanimated (for example for hiding and showing elements I used opacity and reanimated instead of a boolean state change to minimize re-renders). 

Aha woth these notes and points I think I should utilize recoil library. That's amazing trick for reducing the rerenders I will try to use the technique if needed. Thank you.

**Comment by ghorbani-m** [comment]
Dark/light mode feature done #162
